language: go
go:
  - "1.9"
  - "1.10.x"
  - master

branches:
  only:
    - master

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - chmod +x $GOPATH/bin/dep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - dep ensure

script:
  - bash test_covers.sh

sudo: true

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cd6d4e9d-9772-4809-9d93-bfe39c9aca47
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN