language: go
go:
  - "1.9"
  - "1.10.x"
  - master

branches:
  only:
    - master

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - bash test_covers.sh

sudo: true

after_success:
  - bash <(curl -s https://codecov.io/bash) -t cd6d4e9d-9772-4809-9d93-bfe39c9aca47